[project]
name = "data-loader"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "dlt[duckdb,postgres,sql-database]>=1.20.0",
    "apache-airflow[celery,google,graphviz]==3.2.0",
    "fsspec>=2025.12.0",
    "rapidfuzz>=3.14.5",
    "connectorx>=0.4.5",
    "adbc-driver-postgresql>=1.11.0",
    "asyncpg>=0.31.0",
]

[tool.uv.sources]
data-loader = { workspace = true }

[dependency-groups]
dev = [
    "ipython>=9.8.0",
    "ruff>=0.14.10",
]

[tool.ruff.format]
quote-style = "single"
