"""
Upload spotify song streams to the database.
Input file is the parquet generated by dlt_parse_spotify_dump
"""

import dlt
import duckdb
from dlt.sources.filesystem import filesystem, read_parquet

from pathlib import Path

DATA_FILE = Path('/run/media/ola/T5linux/Data/MUSIC/spotify-dump/Streaming_History_Song.parquet')

fs_resource = filesystem(
    str(DATA_FILE.parent),
    file_glob=DATA_FILE.name,
)

PIPELINE_NAME = 'spotify_song_plays'
TABLE_NAME = 'streams'
SCHEMA_NAME = 'spotify'
# dest = dlt.destinations.duckdb(duckdb.connect(':memory:'))
dest = dlt.destinations.postgres()
pipe = fs_resource | read_parquet(use_pyarrow=True).with_name(TABLE_NAME)
pipeline = dlt.pipeline(PIPELINE_NAME, destination=dest)
load_info = pipeline.run(pipe, dataset_name=SCHEMA_NAME)
