[runtime]
log_level = "WARNING"
http_show_error_body = true

# add dlt load metadata when loading dataframes
[normalize.parquet_normalizer]
add_dlt_load_id = true
add_dlt_id = false

[sources.spotify]
api_base = "https://api.spotify.com/v1"
token_url = "https://accounts.spotify.com/api/token"
callback_addr = "127.0.0.1"
callback_port = 3000

[sources.lastfm]
api_base = "https://ws.audioscrobbler.com/2.0"
